export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
export const AUTH_ERROR = 'AUTH_ERROR'

export const SET_EXPERIENCE = 'SET_EXPERIENCE'
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
export const GET_EXPERIENCE = 'GET_EXPERIENCE'
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE'
export const EXPERIENCE_ERROR = 'EXPERIENCE_ERROR'

export const SET_BOOKING = 'SET_BOOKING'
export const ADD_BOOKING = 'ADD_BOOKING'
export const BOOKING_ERROR = 'BOOKING_ERROR'

export const IMAGE_EXPERIENCE = 'IMAGE_EXPERIENCE'
export const IMAGE_ERROR = 'IMAGE_ERROR'